name: CI

on:
  push:
    branches:
      - danielRios_p2_base
      - danielRios_p2_dev
  pull_request:
    branches: [ "danielRios_p2_dev","danielRios_p2_base" ]

  workflow_dispatch:

env: 
  SEM_VERSION: ${{github.run_id}}
  IMAGE_NAME:  "restapp"
  TAG: "1.0.${{ github.run_id }}"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  ## 🔧 1. 
  static-codecheck:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: test
        run: python -m pytest test/unit -v

  ## 🔧 2. 
  build:
    runs-on: self-hosted
    needs: static-codecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: build
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: tag
        run: docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

      - name: push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

  ## 🚀 3. 
  deploy-dev:
    environment:
      name: Develop
    needs: build
    runs-on: [self-hosted, linux]
    if: github.ref == 'refs/heads/danielRios_p2_dev'
    steps:
      - name: Cleanup old containers
        run: |
          docker rm -f redisService-dev || true
          docker rm -f restapp-dev || true

      - name: Deploy Redis
        run: docker run -d --name redisService-dev redis:alpine

      - name: Get Redis IP
        id: redisip
        run: echo "REDIS_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)" >> $GITHUB_ENV

      - name: Deploy REST App
        run: docker run -d --name restapp-dev --add-host redis:$REDIS_IP -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ env.TAG }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Integration Tests
        run: bash ./utils/postmanNeuman_commands.sh


  ## 🚀 4. 
  deploy-prod:
    environment:
      name: Production
    needs: build
    runs-on: [self-hosted, linux]
    if: github.ref == 'refs/heads/danielRios_p2_base'
    steps:
      - name: Cleanup old containers
        run: |
          docker rm -f redisService-prod || true
          docker rm -f restapp-prod || true

      - name: Deploy Redis
        run: docker run -d --name redisService-prod redis:alpine

      - name: Get Redis IP
        id: redisip
        run: echo "REDIS_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)" >> $GITHUB_ENV

      - name: Deploy REST App
        run: docker run -d --name restapp-prod --add-host redis:$REDIS_IP -p 5001:5000 ${{ secrets.DOCKER_USERNAME }}/restapp:${{ env.TAG }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Integration Tests
        run: bash ./utils/postmanNeuman_commands.sh